name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: 13.233.66.146
        username: ec2-user
        key: gopal2.pem
        source: "dist/*"
        target: /home/ec2-user

    - name: Execute remote commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 13.233.66.146
        username: ec2-user
        key: gopal2.pem
        script: |
          cd dist
          npm install -g serve
