name: Continuous Integration

# this is trigger CI on push and PR for main branch only
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# this is trigger CI on all kinds of branches and PRs
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run Build

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY1 }}

      - name: Copy files via scp
        run: scp -o StrictHostKeyChecking=no -r ./dist ec2-user@13.233.66.146:/home/ec2-user/react-ci-cd-pre-commit
